// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1iX91WdJNMTSwUkRbLphPHx4wsebEeUQ',
    appId: '1:383274988747:web:abf015c04e9c0b35b5574e',
    messagingSenderId: '383274988747',
    projectId: 'chatapp-8b52f',
    authDomain: 'chatapp-8b52f.firebaseapp.com',
    storageBucket: 'chatapp-8b52f.appspot.com',
    measurementId: 'G-TZZR61QP6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArFNnBGuChd2Y4_HOljdyTRB3GpOJQ804',
    appId: '1:383274988747:android:b21462a2fc820934b5574e',
    messagingSenderId: '383274988747',
    projectId: 'chatapp-8b52f',
    storageBucket: 'chatapp-8b52f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAugmURpE6ZlCJXQbJe1-_m_2eA_FFark8',
    appId: '1:383274988747:ios:77eaf2a6662a76c2b5574e',
    messagingSenderId: '383274988747',
    projectId: 'chatapp-8b52f',
    storageBucket: 'chatapp-8b52f.appspot.com',
    iosClientId: '383274988747-ni6mqqnmuv98oo00m1llv2gic0mo4fdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAugmURpE6ZlCJXQbJe1-_m_2eA_FFark8',
    appId: '1:383274988747:ios:77eaf2a6662a76c2b5574e',
    messagingSenderId: '383274988747',
    projectId: 'chatapp-8b52f',
    storageBucket: 'chatapp-8b52f.appspot.com',
    iosClientId: '383274988747-ni6mqqnmuv98oo00m1llv2gic0mo4fdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
